name: Create Release

on:
  push:
    tags:
      - 'v*'  # Matches all tags starting with 'v'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get all history for changelog
          
      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Generate release notes
        id: changelog
        run: |
          VERSION=${{ steps.version.outputs.version }}
          echo "Extracting changelog for version $VERSION"
          
          # More robust changelog extraction
          if [ -f "CHANGELOG.md" ]; then
            # Extract content between version headers
            CHANGES=$(sed -n "/^## \[$VERSION\]/,/^## \[/{/^## \[$VERSION\]/d; /^## \[/q; p;}" CHANGELOG.md | sed '/^$/d')
            
            if [ -z "$CHANGES" ]; then
              echo "No changelog found for version $VERSION, using default message"
              CHANGES="Release version $VERSION"
            fi
          else
            echo "CHANGELOG.md not found, using default message"
            CHANGES="Release version $VERSION"
          fi
          
          # Use proper multiline output format
          {
            echo "changes<<EOF"
            echo "$CHANGES"
            echo "EOF"
          } >> $GITHUB_OUTPUT
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release v${{ steps.version.outputs.version }}"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true  # Fallback to auto-generated notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}